version: "3.3"

services:
    postgresdb:
        image: postgres:latest
        container_name: postgresdb
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: openblog
            POSTGRES_DB: OpenBlog
            POSTGRES_PASSWORD: OpenBlog12345
        volumes: 
            - postgres_data:/var/lib/postgresql/data
        deploy:
            restart_policy:
                condition: on-failure
                delay: 10s
        restart: always
        networks:
            - openblog
    openblog:
        build:
            context: ./src/OpenBlog
            dockerfile: Dockerfile
        container_name: openblog
        restart: always
        ports: 
            - "5500:5500"
            - "5402:5402"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 10s
        depends_on: 
            - postgresdb
        networks:
            - openblog
volumes:
    mongodb_data: {}
    postgres_data: {}

networks: 
    openblog:

